source = ~/.config/hypr/colors/hyprlock-colors.conf

background {
    monitor =
    path = ~/wallpapers/lock.png
    color = rgb(11111b)
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 450, 50
    outline_thickness = 3

    outer_color = rgb(cba6f7)
    inner_color = rgb(11111b)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = Enter Password 󰈷 

    check_color = rgb(89b4fa)
    fail_color = rgb(f38ba8)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300

    invert_numlock = false
    swap_font_color = false

    rounding = 6
    shadow_passes = 0
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgb(cdd6f4)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = -5, -500
    halign = center
    valign = center
}

animations {
    enabled = true
}

image {
    monitor =
    path = ~/assets/pic.png
    size = 250
    border_size = 0
    border_color = rgb(cba6f7)
    position = -5, 90
    halign = center
    valign = center
}
